{"Access denied by service policy","تم الرفض من قبل إدارة السيرفر"}.
{"Administrator privileges required","يتطلب صلاحيات الاداره"}.
{"Allow users to change the subject","السماح للزوار بتغيير موضوع الغرفه"}.
{"Allow users to query other users","السماح بالتطلع على نسخة أجهزة المشتركين"}.
{"Allow users to send invites","السماح بإرسال الدعوات لدخول الغرفه"}.
{"Allow users to send private messages","السماح بإستخدام الخاص بالغرفه"}.
{"Allow visitors to change nickname","السماح للزوار بتغيير الإسم المستعار"}.
{"Allow visitors to send private messages to","السماح للزوار بإرسال خاص إلى:"}.
{"Allow visitors to send status text in presence updates","السماح للزوار بإرسال تحديثات رسالة الحاله"}.
{"Allow visitors to send voice requests","السماح للزوار بطلب حق التحدث"}.
{"anyone","الكل"}.
{"A password is required to enter this room","أدخل كلمة المرور المطلوبه للدخول للغرفه"}.
{"April","ابريل"}.
{"August","أغسطس"}.
{"Birthday","تاريخ الميلاد"}.
{"CAPTCHA web page","صفحة الكابتشا"}.
{"Characters not allowed:","هذه الحروف غير مسموح بها :"}.
{"Chatroom configuration modified","تم تعديل برمجة الغرفه"}.
{"Chatroom is created","تم انشاء الغرفه"}.
{"Chatroom is destroyed","تم تدمير الغرفه"}.
{"Chatroom is started","الغرفه فعاله الآن"}.
{"Chatroom is stopped","تم إيقاف الغرفه"}.
{"Chatrooms","الغرف"}.
{"Choose a username and password to register with this server","أكتب إسم المستخدم وكلمة المرور لتسجيل حساب جديد بالسيرفر"}.
{"City","المدينه"}.
{"Conference room does not exist","الغرفه غير موجوده"}.
{"Configuration of room ~s","برمجة واعدادات غرفة  ~s"}.
{"Country","الدوله"}.
{"December","ديسمبر"}.
{"Default users as participants","منح الزوار حق التحدث تلقائيآ"}.
{"Delete","حذف"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","للمزيد من المروريه لا تخبر أحد مطلقا عن كلمة سر حسابك ولا تحتاج ادارة السيرفر لها  فكن منتبها."}.
{"Either approve or decline the voice request.","إقبل أو أرفض طلب حق التحدث"}.
{"Email","البريد الإلكتروني"}.
{"Enable logging","تفعيل تسجيل الغرفه"}.
{"Enter nickname you want to register","أدخل الإسم المستعار المراد تسجيله وإستخدامه ليتم حفظه على السيرفر"}.
{"Enter the text you see","أدخل النص الذي تراه"}.
{"Exclude Jabber IDs from CAPTCHA challenge","إستبعاد السيرفرات التالية من حماية الكابتشا"}.
{"Failed to extract JID from your voice request approval","فشل منح حق التحدث بسبب مشاكل باتصالك"}.
{"Family Name","إسم العائله"}.
{"February","فبراير"}.
{"Filter messages from unaffiliated users through Jabber ID","أدخل إيميل البوت كامل مع الريسورس لفلترة الغرفه"}.
{"Friday","الجمعه"}.
{"Full Name","الإسم بالكامل"}.
{"Grant voice to this person?","منح حق التحدث ؟"}.
{"has been banned","تم فصله"}.
{"has been kicked because of an affiliation change","تم طرده بسبب تغيير بالمنصب"}.
{"has been kicked because of a system shutdown","تم إيقاف أو إعادة تشغيل السيرفر من قبل الإدارة"}.
{"has been kicked because the room has been changed to members-only","الغرفه الآن للأعضاء فقط"}.
{"has been kicked","تم طرده"}.
{" has set the subject to: ","حدد موضوع الغرفه :"}.
{"If you don't see the CAPTCHA image here, visit the web page.","إن لم تتمكن من قراءة الكابتشا هنا من فضلك ادخل الموقع"}.
{"Incorrect password","كلمة سر خاطئه"}.
{"Invalid affiliation: ~s","وظيفه غير صالحه : ~s"}.
{"Invalid role: ~s","دور غير صالح : ~s"}.
{"is now known as","غير إسمه المستعار إلى"}.
{"It is not allowed to send private messages of type \"groupchat\"","غير مسموح بارسال رسائل خاصه"}.
{"It is not allowed to send private messages to the conference","غير مسموح بدخول الخاص بهذه الغرفه"}.
{"It is not allowed to send private messages","غير مسموح بإستخدام رسائل الخاص الآن"}.
{"Jabber Account Registration","تسجيل حساب على السيرفر"}.
{"Jabber ID ~s is invalid","الحساب غير صحيح ~s"}.
{"January","يناير"}.
{"joins the room","إنضم للغرفه"}.
{"July","يوليو"}.
{"June","يونيو"}.
{"leaves the room","غادر الغرفه"}.
{"Make participants list public","السماح بالبحث عن المشتركين بالغرفه"}.
{"Make room CAPTCHA protected","تفعيل حماية الكابتشا"}.
{"Make room members-only","تفعيل الغرفه للأعضاء فقط"}.
{"Make room moderated","تفعيل نظام الإشراف والإداره بالغرفه"}.
{"Make room password protected","تعيين كلمة مرور للغرفه"}.
{"Make room persistent","تفعيل ثبات الغرفه وحفظ البرمجه"}.
{"Make room public searchable","السماح بالبحث عن الغرفه"}.
{"March","مارس"}.
{"Maximum Number of Occupants","الحد الأقصى لعدد الزوار بالغرفه"}.
{"May","مايو"}.
{"Membership is required to enter this room","الغرفه متاحه للأعضاء فقط"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","كلمة المرور يجب ان تكون معروفه لك 100% وذلك لأن ادارة السيرفر لن تعطي احد او تبدل كلمة المرور الخاصه بحسابه حفاظا على سرية بيانات المستخدمين لذلك ضع كلمة المرور سهله بالنسبه لك وليس الاخرين .. توجد برامج هكر تستخرج كلمة المرور بالتخمين لذا الافضل حروف وارقام ورموز ولا تقل عن 10 حروف"}.
{"Middle Name","الاسم الأوسط"}.
{"Minimum interval between voice requests (in seconds)","الفاصل الزمني بين طلبات حق التحدث بالثانية"}.
{"Moderator privileges required","يتطلب صلاحيات المشرفين"}.
{"moderators only","الإداره فقط"}.
{"Monday","الاثنين"}.
{"Name","الإسم"}.
{"New Password:","كلمة المرور الجديده :"}.
{"Nickname Registration at ","تسجيل الإسم المستعار في"}.
{"Nickname ~s does not exist in the room","الإسم غير موجود بالغرفه ~s"}.
{"Nickname","الإسم المستعار"}.
{"nobody","لا أحد"}.
{"No limit","غير محدود"}.
{"No resource provided","لا يوجد ريسورس معروف"}.
{"November","نوفمبر"}.
{"Number of occupants","عدد المتواجدين"}.
{"October","أكتوبر"}.
{"Offline Messages:","رسائل في وضع عدم الاتصال:"}.
{"Old Password:","كلمة المرور القديمة :"}.
{"Only moderators and participants are allowed to change the subject in this room","فقط المديرين والأعضاء مسموح لهم بتحديد أو تغيير موضوع الغرفه"}.
{"Only moderators are allowed to change the subject in this room","فقط المديرين مسموح لهم بتحديد أو تغيير موضوع الغرفه"}.
{"Only moderators can approve voice requests","فقط الاداره تعطي حق التحدث"}.
{"Only occupants are allowed to send messages to the conference","مشتركين الغرفه فقط لديهم حق التحدث"}.
{"Only occupants are allowed to send queries to the conference","المتواجدين فقط يستطيعو إرسال الاستعلامات"}.
{"Only service administrators are allowed to send service messages","فقط ادارة السيرفر تستطيع ارسال رسائل الخدمه"}.
{"Organization Name","جهة العمل"}.
{"Organization Unit","مكان جهة العمل"}.
{"Owner privileges required","يتطلب صلاحيات مالك الغرفه"}.
{"Password Verification:","تأكيد كلمة المرور :"}.
{"Please, wait for a while before sending new voice request","إنتظر فتره قبل إرسال طلب حق التحدث من جديد"}.
{"Present real Jabber IDs to","عرض إيميلات المتواجدين لــ"}.
{"private, ","خاص, "}.
{"Queries to the conference members are not allowed in this room","غير مسموح بالإستعلام عن الأعضاء بهذه الغرفه"}.
{"Recipient is not in the conference room","المستخدم غير موجود بالغرفه أو إنقطع إتصاله ولا يمكنه إستقبال رسالتك"}.
{"Register a Jabber account","تسجيل حساب جديد"}.
{"Register","تسجيل"}.
{"Replaced by new connection","تحديث التواجد باتصال جديد"}.
{"Room Configuration","اعدادات وبرمجة الغرفه"}.
{"Room creation is denied by service policy","غير مسموح بإنشاء غرف من قبل الإدارة"}.
{"Room description","وصف الغرفه"}.
{"Room Occupants","المتواجدين بالغرفه"}.
{"Room title","عنوان الغرفه"}.
{"Saturday","السبت"}.
{"Search users in ","بحث عن مستخدم في  "}.
{"September","سبتمبر"}.
{"Server:","السيرفر :"}.
{"~s invites you to the room ~s","~s قام بدعوتك لدخول هذه الغرفه ~s"}.
{"Some Jabber clients can store your password in your computer. Use that feature only if you trust your computer is safe.","بعض البرامج بالحاسب او الموبايل تحتفظ بكلمة المرور لذلك ننصح بازالتها عند الرغبه بتسجيل الخروج ولذلك نرجو أن نثق فقط ببرنامج السيرفر"}.
{"~s's Offline Messages Queue","ذاكرة الرسائل في وضع عدم الاتصال ~s"}.
{"Sunday","الأحد"}.
{"That nickname is already in use by another occupant","الإسم المستعار مستخدم من قبل مشارك آخر بالغرفه أو تم تسجيله على السيرفر"}.
{"That nickname is registered by another person","الإسم المستعار تم تسجيله من قبل مستخدم آخر"}.
{"The CAPTCHA is valid.","الكابتشا صحيحه"}.
{"The CAPTCHA verification has failed","رمزنص الكابتشا اللذى أدخلته غير صحيح"}.
{"The password is too weak","كلمة المرور ضعيفه جدآ"}.
{"the password is","كلمة المرور هي:"}.
{"The password of your Jabber account was successfully changed.","تم تغيير كلمة مرور حسابك بنجاح"}.
{"There was an error changing the password: ","خطأ عند محاولة تغيير كلمة مرور حسابك :"}.
{"There was an error creating the account: ","خطأ عند محاولة تسجيل الحساب :"}.
{"There was an error deleting the account: ","خطأ عند محاولة حذف الحساب :"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","لا تفرق بين الحروف الكابتل والإسمول حيث أن السيرفر يعاملهم نفس المعامله ."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","تستطيع تسجيل حسابك الجديد من هذه الصفحه فقط قم بملأ الحقول الخاليه :"}.
{"This page allows to unregister a Jabber account in this Jabber server.","تستطيع من هذه الصفحه إلغاء إشتراك حسابك على هذا السيرفر"}.
{"This participant is kicked from the room because he sent an error message to another participant","تم طرد المستخدم بسبب إرساله رساله خاطئه لمشارك آخر"}.
{"This participant is kicked from the room because he sent an error message","تم طرد المستخدم بسبب إرساله رساله خاطئه أو نتيجه لخطأ بإتصاله"}.
{"This participant is kicked from the room because he sent an error presence","تم إستبعاده لوجود مشاكل بإتصال حسابه"}.
{"This room is filtered by external service","هذه الغرفه تستخدم الفلتره"}.
{"This room is not anonymous","الأعضاء غير المعروفين لا يمكنهم دخول الغرفه"}.
{"Thursday","الخميس"}.
{"Too many CAPTCHA requests","تم طلب الكابتشا أكثر من مره ... احذر سيتم حجبك نهائيا"}.
{"Traffic rate limit is exceeded","تم تجاوز حد معدل الإرسال بالغرفه"}.
{"Tuesday","الثلاثاء"}.
{"Unable to generate a CAPTCHA","لا يمكن تبديل الكابتشا عشوائيا .. راسل إدارة السيرفر لحل مشكلتك"}.
{"Unregister a Jabber account","حذف حسابك"}.
{"Unregister","إلغاء حسابي"}.
{"Use of STARTTLS required","يتطلب استخدام STARTTLS"}.
{"User JID","ايميل المستخدم"}.
{"Username:","إسم المستخدم :"}.
{"Users are not allowed to register accounts so quickly","يجب الإنتظار مده كافيه لإعادة تسجيل حساب جديد"}.
{"User","إسم المستخدم"}.
{"Visitors are not allowed to change their nicknames in this room","غير مسموح للزوار بتغيير الإسم المستعار بهذه الغرفه"}.
{"Visitors are not allowed to send messages to all occupants","ليس لديك حق التحدث"}.
{"Voice requests are disabled in this conference","طلب حق التحدث غير مفعل بالغرفه في الوقت الحالي"}.
{"Voice request","طلب حق تحدث"}.
{"Wednesday","الأربعاء"}.
{"You can later change your password using a Jabber client.","تستطيع تغيير كلمة المرور بالمستقبل .. حاول وضع كلمة صعبه ارقام وحروف ورموز ولا تقل عن 10 حروف."}.
{"You have been banned from this room","إيميلك أو سيرفر إيميلك مفصول بهذه الغرفه"}.
{"You must fill in field \"Nickname\" in the form","يجب أن تدخل الإسم المستعار بالمربع"}.
{"You need a client that supports x:data and CAPTCHA to register","تحتاج لبرنامج يعرض صور كلمات التحقق عند التسجيل"}.
{"Your active privacy list has denied the routing of this stanza.","الخصوصية اللتى تم تفعيلها تمنع الإضافات والغرف غير المسجله بحسابك"}.
{"Your contact offline message queue is full. The message has been discarded.","الرسائل فى وضع عدم الإتصال إمتلأت لهذا المستخدم يرجى إرسال رسالتك حين إتصاله مجددآ"}.
{"Your Jabber account was successfully created.","تم تسجيل حسابك بنجاح"}.
{"Your Jabber account was successfully deleted.","تم حذف حسابك بنجاح"}.
