{"Access Configuration","اعدادات الصلاحيات"}.
{"Access Control List Configuration","اعدادات قائمة التحكم بالصلاحيات"}.
{"Access Control Lists","قوائم التحكم بالصلاحيات"}.
{"Access control lists","قوائمة التحكم بالصلاحيات"}.
{"Access denied by service policy","الصلاحيات غير كافيه لتنفيذ المطلوب .. راجع ادارة السيرفر"}.
{"Access rules","قواعد الصلاحيات"}.
{"Access Rules","قواعد الصلاحيات"}.
{"Action on user","تعديل المستخدم"}.
{"Add Jabber ID","اضافة Jabber ID"}.
{"Add New","اضف جديد"}.
{"Add User","اضافة مستخدم"}.
{"Administration of ","ادارة الـ "}.
{"Administration","الاداره"}.
{"Administrator privileges required","يتطلب صلاحيات الاداره"}.
{"A friendly name for the node","اسم السيرفر الاساسي كما يظهر للأصدقاء"}.
{"All activity","كل النشاطات"}.
{"Allow this Jabber ID to subscribe to this pubsub node?","اتسمح لهذا المستخدم بالاشتراك في بوب سب للسيرفر الاساسي?"}.
{"Allow users to change the subject","السماح لغير الاداره بتغيير الروم"}.
{"Allow users to query other users","السماح للمستخدمين بالاستعلام عن المستخدمين الآخرين"}.
{"Allow users to send invites","السماح للمستخدمين بارسال دعوات لدخول الروم"}.
{"Allow users to send private messages","السماح للمستخدمين بارسال الرسائل الخاصه"}.
{"Allow visitors to change nickname","السماح للزوار بتغيير اللقب"}.
{"Allow visitors to send private messages to","الزوار ترسل الرسائل الخاص لــ"}.
{"Allow visitors to send status text in presence updates","السماح للزوار بارسال تحديثات رساله الحاله"}.
{"Allow visitors to send voice requests","السماح للزوار بطلب حق التحدث"}.
{"Announcements","الاعلانات"}.
{"anyone","الجميع"}.
{"A password is required to enter this room","ادخل كلمة سر دخول الروم لتسطيع الدخول"}.
{"April","ابريل"}.
{"August","أغسطس"}.
{"Backup Management","ادارة النسخ الاحتياطي"}.
{"Backup of ","نسخه احتياطيه من "}.
{"Backup to File at ","نسخ احتياطي كملف في  "}.
{"Backup","نسخ احتياطي"}.
{"Bad format","صيغه غير منسقه"}.
{"Birthday","تاريخ الميلاد"}.
{"CAPTCHA web page","صفحة رمز المرور"}.
{"Change Password","تغيير كلمة السر"}.
{"Change User Password","تعديل كلمة سر المستخدم"}.
{"Characters not allowed:","هذه الحروف غير مسموح بها:"}.
{"Chatroom configuration modified","تغّيرت اعدادات الروم"}.
{"Chatroom is created","تم انشاء الروم"}.
{"Chatroom is destroyed","تم تدمير الروم"}.
{"Chatroom is started","الروم فعال الآن"}.
{"Chatroom is stopped","تم ايقاف الروم"}.
{"Chatrooms","الرومات"}.
{"Choose a username and password to register with this server","حدد الاسم وكلمة السر لتسجيل حسابك بالسيرفر"}.
{"Choose modules to stop","اختر الاضافه لايقافها"}.
{"Choose storage type of tables","اختر نوع تخزين البيانات بالجداول "}.
{"Choose whether to approve this entity's subscription.","اختار الطقس ليتم تفعيل اشتراكك"}.
{"City","المدينه"}.
{"Commands","الاوامر"}.
{"Conference room does not exist","الروم غير متاحه بالوقت الحالي"}.
{"Configuration of room ~s","برمجة واعدادات روم  ~s"}.
{"Configuration","الاعدادات"}.
{"Connected Resources:","الريسورس:"}.
{"Connections parameters","الاتصالات"}.
{"Country","الدوله"}.
{"CPU Time:","قوة المعالج:"}.
{"Database Tables at ","جداول البيانات في  "}.
{"Database Tables Configuration at ","اعدادات جداول قواعد البيانات لـ "}.
{"Database","قواعد البيانات"}.
{"December","ديسمبر"}.
{"Default users as participants","منح الزوار حق التحدث"}.
{"Delete message of the day on all hosts","مسح رسالة اليوم لجميع السيرفرات"}.
{"Delete message of the day","مسح رسالة اليوم"}.
{"Delete Selected","مسح المعلّم"}.
{"Delete User","مسح مستخدم"}.
{"Delete","حذف"}.
{"Deliver event notifications","تسليم تنبيهات الاشتراك"}.
{"Deliver payloads with event notifications","تسليم اشعارات مع تنبيهات الاشتراك"}.
{"Description:","الوصف:"}.
{"Disc only copy","بالهارد"}.
{"Displayed Groups:","عرض المجموعات:"}.
{"Don't tell your password to anybody, not even the administrators of the Jabber server.","للمزيد من السريه لا تخبر أحد مطلقا عن كلمة سر حسابك ولا تحتاج ادارة السيرفر لها  فكن منتبها."}.
{"Dump Backup to Text File at ","نسخ احتياطي في صورة ملف نصي في "}.
{"Dump to Text File","الحفظ كملف نصي"}.
{"Edit Properties","تعديل الخصائص"}.
{"Either approve or decline the voice request.","اقبل او ارفض طلب حق التحدث"}.
{"ejabberd IRC module","ejabberd IRC اضافة"}.
{"ejabberd MUC module","ejabberd MUC اضافة"}.
{"ejabberd Publish-Subscribe module","اضافة اشتراك-النشر"}.
{"ejabberd SOCKS5 Bytestreams module","ejabberd SOCKS5 Bytestreams модуль"}.
{"ejabberd vCard module","vCard اضافة"}.
{"ejabberd Web Admin","لوحة تحكم السيرفر"}.
{"Elements","العناصر"}.
{"Email","الايميل"}.
{"Enable logging","تفعيل المحفوظات"}.
{"Encoding for server ~b","ترميز السيرفر ~b"}.
{"End User Session","قطع اتصال المستخدم"}.
{"Enter list of {Module, [Options]}","ادخل قائمة الاضافات كالمثال {Module, [Options]}"}.
{"Enter nickname you want to register","ادخل اللقب الذي تود تسجيله"}.
{"Enter path to backup file","مسار ملف النسخ الاحتياطي"}.
{"Enter path to jabberd14 spool dir","ادخال مسار ملف jabberd14"}.
{"Enter path to jabberd14 spool file","ادخال مسار الى ملف jabberd14"}.
{"Enter path to text file","ادخل مسار ملف النسخ الاحتياطي النصي"}.
{"Enter the text you see","أدخل النص الذي تراه"}.
{"Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings.","Enter username and encodings you wish to use for connecting to IRC servers.  Press 'Next' to get more fields to fill in.  Press 'Complete' to save settings."}.
{"Enter username, encodings, ports and passwords you wish to use for connecting to IRC servers","ادخل اللقب ونظام الترميز والبورت والباسورد التي تود استخدامها للاتصال بــ IRC سيرفرات "}.
{"Erlang Jabber Server","سيرفر جابر مبني بلغة ايرلانج"}.
{"Error","خطأ"}.
{"Example: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}].","مثال: [{\"irc.lucky.net\", \"koi8-r\", 6667, \"secret\"}, {\"vendetta.fef.net\", \"iso8859-1\", 7000}, {\"irc.sometestserver.net\", \"utf-8\"}]."}.
{"Exclude Jabber IDs from CAPTCHA challenge","الاستثناءات من حماية دخول الروم برمز مرور"}.
{"Export data of all users in the server to PIEFXIS files (XEP-0227):","تصدير بيانات المستخدمين الى ملف نوعه PIEFXIS (XEP-0227):"}.
{"Export data of users in a host to PIEFXIS files (XEP-0227):","تصدير بيانات المستخدمين في جميع السيرفرات الى ملف نوعه PIEFXIS (XEP-0227):"}.
{"Failed to extract JID from your voice request approval","فشل منح حق التحدث بسبب مشاكل باتصالك"}.
{"Family Name","اسم العائله"}.
{"February","فبراير"}.
{"Fill in fields to search for any matching Jabber User","املأ الحقول لنرى ماذا يطابق بحثك"}.
{"Fill in the form to search for any matching Jabber User (Add * to the end of field to match substring)","فشل العثور على مستخدم كما بحثت (أضف * بنهاية كلمة البحث поля, то происходит поиск подстроки)"}.
{"Friday","الجمعه"}.
{"From ~s","من ~s"}.
{"From","من"}.
{"Full Name","الاسم بالكامل"}.
{"Get Number of Online Users","عرض عدد المتصلين الآن"}.
{"Get Number of Registered Users","عرض عدد الأعضاء المسجلين"}.
{"Get User Last Login Time","عرض اخر دخول للمستخدم"}.
{"Get User Password","عرض كلمة سر المستخدم"}.
{"Get User Statistics","عرض احصائيات مستخدم"}.
{"Grant voice to this person?","منح حق التحدث ؟"}.
{"Groups","المجموعات"}.
{"Group ","مجموعة "}.
{"has been banned","تم فصله"}.
{"has been kicked because of an affiliation change","выгнали из комнаты вследствие смены ранга"}.
{"has been kicked because of a system shutdown","تم طرده لأن السيرفر تم اغلاقه من قبل ادارة السيرفر"}.
{"has been kicked because the room has been changed to members-only","تم طرده لأن الروم أصبحت للأعضاء فقط"}.
{"has been kicked","تم طرده"}.
{" has set the subject to: "," حدد الموضوع كــ: "}.
{"Host","السيرفر"}.
{"If you don't see the CAPTCHA image here, visit the web page.","لا ترى صورة رمز المرور قم بزيارة صفحة رمز المرور او الموقع الرسمي للسيرفر او تواصل مع ادارة السيرفر لحل المشكله"}.
{"If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password.","If you want to specify different ports, passwords, encodings for IRC servers, fill this list with values in format '{\"irc server\", \"encoding\", port, \"password\"}'.  By default this service use \"~s\" encoding, port ~p, empty password."}.
{"Import Directory","استعادة مجلد نسخه احتياطيه"}.
{"Import File","استعادة نسخه احتياطيه"}.
{"Import user data from jabberd14 spool file:","استيراد بيانات المستخدمين من ملف نوعه jabberd14:"}.
{"Import User from File at ","استرجاع المستخدمين من ملفي في "}.
{"Import users data from a PIEFXIS file (XEP-0227):","استيراد بيانات المستخدمين من ملف نوعه PIEFXIS (XEP-0227):"}.
{"Import users data from jabberd14 spool directory:","استيراد بيانات المستخدمين من مجلد كامل من النوع  jabberd14:"}.
{"Import Users from Dir at ","استرجاع المستخدمين من مجلد في "}.
{"Import Users From jabberd14 Spool Files","استعادة المستخدمين من ملف  jabberd14"}.
{"Improper message type","رساله خاطئه"}.
{"Incorrect password","كلمة سر خاطئه"}.
{"Invalid affiliation: ~s","وظيفه صالحه: ~s"}.
{"Invalid role: ~s","دور صالح: ~s"}.
{"IP addresses","عنوان الاي بي"}.
{"IP","اي بي"}.
{"IRC channel (don't put the first #)","قناة IRC (لا تضع بأول الاسم #)"}.
{"IRC server","سيرفر الـ IRC"}.
{"IRC settings","خيارات IRC"}.
{"IRC Transport","IRC ترانسبورت"}.
{"IRC username","اسم IRC"}.
{"IRC Username","اسم IRC"}.
{"is now known as","أصبح معروفا بـ "}.
{"It is not allowed to send private messages of type \"groupchat\"","غير مسموح بارسال رسائل خاصه اكتب بـ  \"العام\""}.
{"It is not allowed to send private messages to the conference","Не разрешается посылать частные сообщения прямо в конференцию"}.
{"It is not allowed to send private messages","لا يمكن ارسال رسائل خاصه"}.
{"Jabber Account Registration","امتلك حساب بأقوى سيرفر عربي"}.
{"Jabber ID","Jabber ID"}.
{"Jabber ID ~s is invalid","Jabber ID ~s مقبول"}.
{"January","يناير"}.
{"Join IRC channel","دخول قناة IRC"}.
{"joins the room","دخل الروم"}.
{"Join the IRC channel here.","دخول قناة IRC"}.
{"Join the IRC channel in this Jabber ID: ~s","دخول قناة IRC بــ Jabber ID: ~s"}.
{"July","يوليه"}.
{"June","يونيه"}.
{"Last Activity","آخر نشاط"}.
{"Last login","آخر تسجيل دخول"}.
{"Last month","الشهر الأخير"}.
{"Last year","العام الأخير"}.
{"leaves the room","غادر الروم"}.
{"Listened Ports at ","بورتات الاتصال في  "}.
{"Listened Ports","البورتات "}.
{"List of modules to start","قائمة الاضافات لتفعيلها"}.
{"Low level update script","المستوى الأدنى لترقية السيرفر ككل"}.
{"Make participants list public","عرض المتواجدين بالروم في  البحث"}.
{"Make room CAPTCHA protected","تفعيل حماية دخول الروم برمز مرور"}.
{"Make room members-only","وضع الروم للأعضائ فقط"}.
{"Make room moderated","تفعيل نظام الاشرف والاداره بالروم"}.
{"Make room password protected","وضع كلمة سر لدخول الروم"}.
{"Make room persistent","تفعيل ثبات الروم وحفظ البرمجه"}.
{"Make room public searchable","عرض الروم للجميع في البحث"}.
{"March","مارس"}.
{"Maximum Number of Occupants","أقصى عدديتواجد بنفس الوقت في الروم"}.
{"Max # of items to persist","الحد الأقصى للبيانات المخزنه"}.
{"Max payload size in bytes","الحد الاقصى لحجم البيانات"}.
{"May","مايو"}.
{"Membership is required to enter this room","الروم متاح للأعضاء فقط"}.
{"Members:","الأعضاء:"}.
{"Memorize your password, or write it in a paper placed in a safe place. In Jabber there isn't an automated way to recover your password if you forget it.","كلمة السر يجب ان تكون معروفه لك 100% وذلك لأن ادارة السيرفر لن تعطي احد او تبدل كلمة سره حفاظا على سرية بيانات المستخدمين نكرر ضعها سهله بالنسبه لك وليس الاخرين .. توجد برامج هكر تستخرج كلمة السر بالتخمين لذا الافضل حروف وارقام ورموز ولا تقل عن 10 حروف"}.
{"Memory","الذاكره"}.
{"Message body","رسائل الروم"}.
{"Middle Name","الاسم الأوسط"}.
{"Minimum interval between voice requests (in seconds)","الفاصل الزمني بين طلبات حق التحدث بالثانية"}.
{"Moderator privileges required","يتطلب صلاحيات المشرفين"}.
{"moderators only","الاداره فقط"}.
{"Modified modules","تعديل الاضافات"}.
{"Modules at ","الاضافات في  "}.
{"Modules","الاضافات"}.
{"Module","اضافه"}.
{"Monday","الاثنين"}.
{"Name:","الاسم:"}.
{"Name","الاسم"}.
{"Never","أبدا"}.
{"New Password:","كلمة السر الجديده:"}.
{"Nickname Registration at ","تسجيل اللقب في "}.
{"Nickname ~s does not exist in the room","لقب ~s غير مسموح به في الروم"}.
{"Nickname","اللقب"}.
{"No body provided for announce message","لا يوجد نص للاعلان ... اعلان قصير جدا"}.
{"nobody","لا أحد"}.
{"No Data","لا توجد بيانات لعرضها"}.
{"Node ID","عنوان السيرفر الاساسي"}.
{"Node not found","السيرفر الاساسي غير موجود"}.
{"Nodes","السيرفرات الأساسيه"}.
{"Node ","سيرفر اساسي  "}.
{"No limit","غير محدود"}.
{"None","غير معروف"}.
{"No resource provided","لا يوجد ريسورس معروف"}.
{"Not Found","غير موجود"}.
{"Notify subscribers when items are removed from the node","اخبر المشتركين عند مسحهم من السيرفر الاساسي"}.
{"Notify subscribers when the node configuration changes","اخبار المشتركين عند تغيير السيرفر الاساسي"}.
{"Notify subscribers when the node is deleted","اخبار المشتركين عند مسح السيرفر الاساسي"}.
{"November","نوفمبر"}.
{"Number of occupants","عدد المتواجدين"}.
{"Number of online users","عدد الاعضاء المتصلين الآن"}.
{"Number of registered users","عدد المستخدمين المسجلين"}.
{"October","أكتوبر"}.
{"Offline Messages","رسائل في وضع عدم اتصال"}.
{"Offline Messages:","رسائل في وضع عدم الاتصال:"}.
{"OK","موافق"}.
{"Old Password:","كلمة السر القديمة:"}.
{"Online Users","المستخدمين المتصلين"}.
{"Online Users:","المستخدمين المتصلين الآن:"}.
{"Online","متصل"}.
{"Only deliver notifications to available users","فقط المستخدمين في وضع متاح من يستقبلون التنبيهات"}.
{"Only moderators and participants are allowed to change the subject in this room","الاداره والمشتركين مسموح لهم بتغيير الموضوع بالروم"}.
{"Only moderators are allowed to change the subject in this room","ادارة الروم فقط يسمح لها بتعديل الموضوع"}.
{"Only moderators can approve voice requests","فقط الاداره تعطي حق التحدث"}.
{"Only occupants are allowed to send messages to the conference","فقط المتواجدين بالروم يستطيعو ارسال رسائل خاصه"}.
{"Only occupants are allowed to send queries to the conference","المتواجدين فقط يستطيعو ارسال الاستعلامات"}.
{"Only service administrators are allowed to send service messages","فقط ادارة السيرفر تستطيع ارسال رسائل الخدمه"}.
{"Options","خيارات"}.
{"Organization Name","جهة العمل"}.
{"Organization Unit","مكان جعة العمل"}.
{"Outgoing s2s Connections:","اتصالات صادرة:"}.
{"Outgoing s2s Connections","اتصالات صادره "}.
{"Outgoing s2s Servers:","ارتباطات الاتصالات الصادره:"}.
{"Owner privileges required","يتطلب صلاحيات مالك الروم"}.
{"Packet","مجموعه"}.
{"Password ~b","كلمة السر ~b"}.
{"Password Verification:","تأكيد كلمة السر:"}.
{"Password Verification","تأكيد كلمة السر"}.
{"Password:","كلمة السر:"}.
{"Password","كلمة السر"}.
{"Path to Dir","مسار المجلد"}.
{"Path to File","مسار الملف"}.
{"Pending","بالانتظار"}.
{"Period: ","مـدة"}.
{"Persist items to storage","تثبيت اختيارات التخزين"}.
{"Ping","سرعه"}.
{"Please note that these options will only backup the builtin Mnesia database. If you are using the ODBC module, you also need to backup your SQL database separately.","لاحظ هذا الخيار فقط لقولعد البيانات المدمجه  اذا كنت تستخدم قواعد بيانات odbc ستحتاج لأخذ نسخه احتياطيه من قاعدة بياناتك قد تكون من النوع mysql او من النوع postgres"}.
{"Please, wait for a while before sending new voice request","الرجاء الانتظار لحظات قبل ارسال طلب حق تحدث جديد"}.
{"Pong","سرعة"}.
{"Port ~b","البورت ~b"}.
{"Port","البورت"}.
{"Present real Jabber IDs to","عرض ايميلات المتواجدين لــ"}.
{"private, ","خاص, "}.
{"Protocol","بروتوكول "}.
{"Publish-Subscribe","اشتراك-النشر"}.
{"PubSub subscriber request","طلب الانضمام لـ بوب سب"}.
{"Purge all items when the relevant publisher goes offline","اخبر الجميع عندما يتغير حالة الناشر لاوف لاين"}.
{"Queries to the conference members are not allowed in this room","الاستعلام عن اعضاء الروم غير مسموح به في هذه الغرفه"}.
{"RAM and disc copy","بالرام والهارد"}.
{"RAM copy","بالرام"}.
{"Raw","الاعدادات الاساسيه الحاليه اجمالا"}.
{"Really delete message of the day?","أكد قرارك بحذف الرسائل"}.
{"Recipient is not in the conference room","المستخدم غير موجود بالروم او انقطع اتصاله ولا يمكن استقبال رسالتك"}.
{"Register a Jabber account","تسجيل حساب جديد"}.
{"Registered Users","الأعضاء المسجلين"}.
{"Registered Users:","المستخدمين المسجلين:"}.
{"Register","التسجيل"}.
{"Registration in mod_irc for ","التسجيل في mod_irc من اجل "}.
{"Remote copy","نسخ خارجي"}.
{"Remove All Offline Messages","مسح كافة الرسائل في وضع عدم الاتصال"}.
{"Remove User","مسح مستخدم"}.
{"Remove","حذف"}.
{"Replaced by new connection","تحديث التواجد باتصال جديد"}.
{"Resources","الريسورس"}.
{"Restart Service","اعادة تشغيل السيرفر"}.
{"Restart","اعادة تشغيل"}.
{"Restore Backup from File at ","استرجاع نسخ احتياطي من "}.
{"Restore binary backup after next ejabberd restart (requires less memory):","استعادة نسخه احتياطيه ثنايه مع اعادة تشغيل السيرفر (يتطلب  استهلاك بعض الرام):"}.
{"Restore binary backup immediately:","استعادة نسخه احتياطيه ثنائيه:"}.
{"Restore plain text backup immediately:","استرجاع نسخه احتياطيه من النصوص:"}.
{"Restore","استعادة"}.
{"Room Configuration","اعدادات وبرمجة الروم"}.
{"Room creation is denied by service policy","انشاء الروم غير متاح بالوقت الحالي"}.
{"Room description","وصف الروم"}.
{"Room Occupants","المتواجدين بالروم"}.
{"Room title","عنوان الروم"}.
{"Roster groups allowed to subscribe","مجموعات الاضافات مسموح لها بالاشتراك"}.
{"Roster of ","اضافات  "}.
{"Roster size","حجم الاضافات"}.
{"Roster","اضافات"}.
{"RPC Call Error","خطأ بالاتصال RPC"}.
{"Running Nodes","اسماء السيرفرات الفعاله"}.
{"~s access rule configuration","اعدادات قواعد الصلاحيات ~s"}.
{"Saturday","السبت"}.
{"Script check","فحص السيرفر"}.
{"Search Results for ","نتائج البحث لــ :  "}.
{"Search users in ","بحث عن مستخدم في  "}.
{"Send announcement to all online users on all hosts","ارسل اعلان للمستخدمين المتصلين الآن بكل السيرفرات"}.
{"Send announcement to all online users","ارسل اعلان للمستخدمين المتصلين الآن"}.
{"September","سبتمبر"}.
{"Server ~b","السيرفر ~b"}.
{"Server:","السيرفر:"}.
{"Set message of the day and send to online users","وضع رسالة اليوم وارسالها للمتصلين الآن"}.
{"Set message of the day on all hosts and send to online users","وضع رسالة اليوم لجميع السيرفرات وارسالها لجميع المستخدمين المتصلين الآن"}.
{"Shared Roster Groups","مجموعات الاضافات المشتركه"}.
{"Show Integral Table","عرض جدول متكامل"}.
{"Show Ordinary Table","عرض جدول منتظم"}.
{"Shut Down Service","ايقاف السيرفر"}.
{"~s invites you to the room ~s","~s دعاك لدخول روم ~s"}.
{"Some Jabber clients can store your password in your computer. Use that feature only if you trust your computer is safe.","بعض البرامج بالحاسب او الموبايل تحتفظ بكلمة السر لذلك ننصح بازالتها عند الرغبه بتسجيل الخروج. ."}.
{"Specify the access model","تعديل صلاحيات الاضافه"}.
{"Specify the event message type","حدد نوع الرساله المكتوبه"}.
{"Specify the publisher model","خصائص اضافة النشر"}.
{"~s's Offline Messages Queue","ذاكرة الرسائل في وضع عدم الاتصال ~s"}.
{"Start Modules at ","تشغيل اضافه لـ "}.
{"Start Modules","تشغيل الاضافات"}.
{"Start","تشغيل"}.
{"Statistics of ~p","الاحصائيات لـ ~p"}.
{"Statistics","الاحصائيات"}.
{"Stop Modules at ","ايقاف اضافة لـ "}.
{"Stop Modules","ايقاف الاضافات"}.
{"Stopped Nodes","اسماء السيرفرات غير الفعاله"}.
{"Stop","ايقاف"}.
{"Storage Type","نوع التخزين"}.
{"Store binary backup:","حفظ نسخه احتياطيه ثنائيه:"}.
{"Store plain text backup:","حفظ نسخه احتياطيه من النصوص:"}.
{"Subject","الموضوع"}.
{"Submitted","اعتمد التعديلات"}.
{"Submit","اعتمد التعديلات"}.
{"Subscriber Address","عنوان الناشر"}.
{"Subscription","مشترك"}.
{"Sunday","الأحد"}.
{"That nickname is already in use by another occupant","لقبك الحالي مستخدم بواسطة مستخدم آخر بالروم .. اختر لقب جديد"}.
{"That nickname is registered by another person","هذا اللقب تم تسجيله من قبل مستخدم آخر"}.
{"The CAPTCHA is valid.","رمز المرور صحيح"}.
{"The CAPTCHA verification has failed","رمز المرور الذي أدخلته غير صحيح"}.
{"The collections with which a node is affiliated","تم الارتباط كليا بالسيرفر الاساسي"}.
{"The password is too weak","كلمة السر ضعيفه"}.
{"the password is","كلمة السر هي:"}.
{"The password of your Jabber account was successfully changed.","تم تغيير كلمة السر لحسابك بنجاح"}.
{"There was an error changing the password: ","حدث خطأ عند تغيير كلمة سر حسابك ... حاول بعد قليل:"}.
{"There was an error creating the account: ","حدث خطأ عند انشاء حسابك ... من فضلك أعد المحاوله بعد قليل:"}.
{"There was an error deleting the account: ","حدث خطأ عند مسح حسابك ... حاول بعد قليل:"}.
{"This is case insensitive: macbeth is the same that MacBeth and Macbeth.","لا تفرق بين الحروف الكابتل والاسمول السيرفر يعاملهم نفس المعامله ."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","تستطيع تسجيل حسابك بالسيرفر  بثواني معدودهفقط قم بملأ الحقول الآتيه"}.
{"This page allows to unregister a Jabber account in this Jabber server.","تستطيع تسجيل حسابك او الغائه"}.
{"This participant is kicked from the room because he sent an error message to another participant","تم طرده لارساله رسالة خطأ او لانقطاع اتصاله عند ارساله رساله لمستخدم آخر"}.
{"This participant is kicked from the room because he sent an error message","تم طرده لارسال رسالة خطأ او نتيجه لمشاكل باتصاله"}.
{"This participant is kicked from the room because he sent an error presence","تم طرده لوجود مشاكل باتصاله"}.
{"This room is not anonymous","الأعضاء غير المعروفين لا يمكنهم دخول الروم"}.
{"Thursday","الخميس"}.
{"Time delay","زمن التأخير"}.
{"Time","الوقت"}.
{"Too many CAPTCHA requests","تم طلب رمز المرور أكثر من مره ... احذر سيتم حجبك نهائيا"}.
{"To ~s","الى ~s"}.
{"To","الى"}.
{"Traffic rate limit is exceeded","تجاوزت معدل تدفق البيانات المسموح به تم حجب رسالتك"}.
{"Transactions Aborted:","عدم اكتمال المعالجه بشكل كامل:"}.
{"Transactions Committed:","اكتمال المعالجه:"}.
{"Transactions Logged:","المعالجة موثقه:"}.
{"Transactions Restarted:","اعادة المعالجه:"}.
{"Tuesday","الثلاثاء"}.
{"Unable to generate a CAPTCHA","لا يمكن تبديل رمز المرور عشوائيا .. لطفا راسل ادارة السيرفر لحل مشكلتك"}.
{"Unauthorized","لا توجد صلاحيات ربما لم تسجل الدخول بعد"}.
{"Unregister a Jabber account","مسح حسابك"}.
{"Unregister","الغاء حسابي"}.
{"Update message of the day (don't send)","تعديل رسالة اليوم (لا ترسلها)"}.
{"Update message of the day on all hosts (don't send)","تعديل رسالة اليوم لكل السيرفرات (لا ترسلها)"}.
{"Update plan","تحديث الخطه"}.
{"Update script","تحديث السيرفر ككل"}.
{"Update ","تحديث "}.
{"Update","تحديث"}.
{"Uptime:","قوة السيرفر:"}.
{"Use of STARTTLS required","يتطلب استخدام STARTTLS"}.
{"User JID","ايميل المستخدم"}.
{"User Management","ادارة المستخدمين"}.
{"Username:","اسم المستخدم:"}.
{"Users are not allowed to register accounts so quickly","يجب الانتظار لمدة لاعادة تسجيل حساب جديد"}.
{"Users Last Activity","آخر نشاطات المستخدمين"}.
{"User","الاسم"}.
{"User ","المستخدم "}.
{"Validate","موافق"}.
{"vCard User Search","بحث عن مستخدم بواسطه بيانات  vCard"}.
{"Virtual Hosts","السيرفرات المستضافه"}.
{"Visitors are not allowed to change their nicknames in this room","الزوار غير مسموح لهم بتغيير ألقابهم بالروم"}.
{"Visitors are not allowed to send messages to all occupants","الزوار ممنوعين من ارسال رسالئل للمتواجدين"}.
{"Voice requests are disabled in this conference","طلب حق التحدث غير مفعل بالروم في الوقت الحالي"}.
{"Voice request","طلب حق تحدث"}.
{"Wednesday","الأربعاء"}.
{"When to send the last published item","عندما ترسل اخر تحديثات"}.
{"Whether to allow subscriptions","الطقس للسماح بالاشتراك"}.
{"You can later change your password using a Jabber client.","تستطيع تغيير كلمة السر بالمستقبل .. حاول وضع كلمة صعبه ارقام وحروف ورموز ولا تقل عن 10 حروف."}.
{"You have been banned from this room","ايميلك او سيرفر  ايميلك ككل غير مصرح له بدخول الروم"}.
{"You must fill in field \"Nickname\" in the form","استكمل الحق  \"اللقب\" في النموذج"}.
{"You need a client that supports x:data and CAPTCHA to register","تحتاج لبرنامج يعرض صور كلمات التحقق عند التسجيل"}.
{"You need a client that supports x:data to register the nickname","تحتاج لبرنامج تسجل به دخولك, يدعم x:data "}.
{"You need an x:data capable client to configure mod_irc settings","لتعديل  mod_irc, تحتاج الى برنامج وتسجيل دخولك x:data على ان يتوافق البربنامج وبروتوكول السيرفر"}.
{"You need an x:data capable client to configure room","تحتاج برنامج وتسجيل دخولك بحساب اونر, x:data لتعدل برمجة الروم"}.
{"You need an x:data capable client to search","تحتاج لتسجيل دخولك من برنامج يدعم x:data"}.
{"Your active privacy list has denied the routing of this stanza.","تم رفض البيانات من ادارة السيرفر."}.
{"Your contact offline message queue is full. The message has been discarded.","لا يمكنني استقبال رسالتك.. لا توجد ذاكره .. لذلك من فضلك اعد ارسالها عند اتصالي"}.
{"Your Jabber account was successfully created.","تم انشاء حسابك بنجاح .... شكرا لانضمامك."}.
{"Your Jabber account was successfully deleted.","تم مسح حسابك بنجاح."}.
{"Your messages to ~s are being blocked. To unblock them, visit ~s","رسالتك لـ  ~s مرفوضه لعرضها قم بزيارة ~s"}.
